# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aOpVKLKOnpghRXGblId4ykD2RpQF8yC
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import torch
from transformers import T5ForConditionalGeneration, T5Tokenizer
import re
import gc
from datetime import datetime
import logging
from contextlib import asynccontextmanager

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class Query(BaseModel):
    question: str

class HealthResponse(BaseModel):
    status: str
    timestamp: str
    model_loaded: bool

model = None
tokenizer = None
device = None

comprehensive_legal_dataset = [
    {"context": "what is ipc section 279", "response": "IPC Section 279 deals with rash driving or riding on a public way, endangering human life or causing hurt. It covers negligent acts that could potentially harm others on public roads."},
    {"context": "define ipc section 279", "response": "Section 279 is defined as rash driving or riding on a public way that endangers human life or is likely to cause hurt or injury to any other person."},
    {"context": "ipc 279 meaning", "response": "IPC 279 means driving or riding a vehicle rashly or negligently on public roads in a manner that endangers human life or safety."},
    {"context": "section 279 ipc definition", "response": "Section 279 IPC defines the offense of rash or negligent driving/riding on public ways that endangers life or causes hurt."},
    {"context": "what does section 279 say", "response": "Section 279 states that whoever drives any vehicle or rides on any public way so rashly or negligently as to endanger human life shall be punished."},
    {"context": "section 279 indian penal code", "response": "Section 279 of the Indian Penal Code criminalizes rash or negligent driving on public ways that endangers human life or causes physical harm."},
    {"context": "279 ipc full text", "response": "IPC 279 states: Whoever drives any vehicle, or rides, on any public way so rashly or negligently as to endanger human life, or to be likely to cause hurt or injury to any other person, shall be punished with imprisonment of either description for a term which may extend to six months, or with fine which may extend to one thousand rupees, or with both."},
    {"context": "ipc section 279 punishment", "response": "The punishment for IPC Section 279 includes imprisonment up to 6 months, fine up to Rs. 1000, or both. The court decides based on case severity."},
    {"context": "what is punishment for section 279", "response": "Section 279 punishment can be imprisonment for up to 6 months, or fine up to Rs. 1000, or both imprisonment and fine together."},
    {"context": "penalty for ipc 279", "response": "The penalty under IPC 279 is imprisonment up to 6 months, fine up to Rs. 1000, or both depending on the circumstances and court's discretion."},
    {"context": "jail time for section 279", "response": "The maximum jail time for Section 279 is 6 months, though courts may award lesser punishment based on case facts."},
    {"context": "fine amount for ipc 279", "response": "The maximum fine for IPC 279 is Rs. 1000, though courts may impose lesser amounts based on the severity of the offense."},
    {"context": "is section 279 bailable", "response": "Yes, IPC Section 279 is a bailable offense. Bail can be granted by police or magistrate depending on circumstances."},
    {"context": "section 279 cognizable or non cognizable", "response": "Section 279 is a cognizable offense, meaning police can arrest without warrant and investigate without court permission."},
    {"context": "rash driving section 279", "response": "Rash driving under Section 279 includes overspeeding, dangerous overtaking, signal jumping, zigzag driving, and any driving that endangers public safety."},
    {"context": "negligent driving 279", "response": "Negligent driving under Section 279 means driving without proper care and attention, endangering others due to lack of reasonable precautions."},
    {"context": "examples of section 279", "response": "Examples of Section 279: Overspeeding in crowded areas, running red lights, dangerous overtaking, driving under influence, using mobile while driving, not maintaining safe distance."},
    {"context": "section 279 case laws", "response": "Important case laws: State of Karnataka v. Krishnappa (rash driving definition), Kurban Hussein v. State of Bihar (negligence standards), Alister Anthony Pareira v. State of Maharashtra (burden of proof)."},
    {"context": "how to prove section 279", "response": "To prove Section 279: Establish rash/negligent driving, show endangerment to human life, provide witness testimony, CCTV footage, expert evidence, and demonstrate causation."},
    {"context": "section 279 defense", "response": "Defense against Section 279: Prove no rash/negligent driving, emergency situation, mechanical failure, other driver's fault, lack of endangerment, or procedural violations."},
    {"context": "what is ipc section 304a", "response": "IPC Section 304A deals with causing death by negligence - when someone's negligent act causes death without intention to cause death or knowledge that the act is likely to cause death."},
    {"context": "define section 304a", "response": "Section 304A defines the offense of causing death by negligence, where death is caused by a negligent act not amounting to culpable homicide."},
    {"context": "304a ipc meaning", "response": "IPC 304A means causing death through negligent acts without intention to kill or knowledge that such acts would likely cause death."},
    {"context": "punishment for 304a", "response": "IPC Section 304A punishment includes imprisonment up to 2 years, or fine, or both. The punishment is less severe than intentional murder."},
    {"context": "medical negligence 304a", "response": "Medical negligence causing death can attract Section 304A if doctor's negligent treatment, wrong medication, or surgical errors result in patient's death."},
    {"context": "road accident death 304a", "response": "Road accidents causing death due to negligent driving are commonly prosecuted under Section 304A along with Section 279."},
    {"context": "section 304a elements", "response": "Elements of Section 304A: Death of a person, caused by accused's act, act was negligent, no intention to cause death, no knowledge that act likely to cause death."},
    {"context": "difference between 302 and 304a", "response": "Section 302 is murder with intention/knowledge to cause death. Section 304A is death by negligence without intention or knowledge of likely death."},
    {"context": "304a bailable or not", "response": "Section 304A is generally bailable, but court discretion applies based on circumstances. High courts often grant bail considering the negligent nature."},
    {"context": "how to prove 304a", "response": "To prove 304A: Establish death occurred, show negligent act by accused, prove causation between negligent act and death, demonstrate lack of intention."},
    {"context": "section 304a case studies", "response": "Common 304A cases: Medical negligence deaths, construction site accidents, industrial accidents, rash driving fatalities, food poisoning deaths, building collapses."},
    {"context": "304a examples", "response": "Examples of 304A: Doctor prescribing wrong medicine, driver hitting pedestrian negligently, contractor using substandard materials, factory owner ignoring safety."},
    {"context": "what is ipc section 337", "response": "IPC Section 337 deals with causing hurt by rash or negligent acts that endanger human life or personal safety of others."},
    {"context": "what is ipc section 338", "response": "IPC Section 338 deals with causing grievous hurt by rash or negligent acts that endanger human life or personal safety."},
    {"context": "difference between 337 and 338", "response": "Section 337 deals with simple hurt (minor injuries) while Section 338 deals with grievous hurt (serious injuries like fractures or permanent damage)."},
    {"context": "section 337 punishment", "response": "Section 337 punishment: Imprisonment up to 6 months, or fine up to Rs. 500, or both for causing simple hurt by negligent acts."},
    {"context": "section 338 punishment", "response": "Section 338 punishment: Imprisonment up to 2 years, or fine up to Rs. 1000, or both for causing grievous hurt by negligent acts."},
    {"context": "simple hurt definition", "response": "Simple hurt under Section 319: Voluntarily causing bodily pain, disease or infirmity without causing grievous hurt. Includes minor cuts, bruises, swelling."},
    {"context": "grievous hurt definition", "response": "Grievous hurt under Section 322: Emasculation, permanent disfiguring, fracture/dislocation of bone, tooth/nail damage, powers of limb/organ permanently impairing."},
    {"context": "337 vs 323 difference", "response": "Section 323 is voluntarily causing hurt with intention. Section 337 is causing hurt by rash/negligent acts without intention to hurt."},
    {"context": "338 vs 325 difference", "response": "Section 325 is voluntarily causing grievous hurt with intention. Section 338 is causing grievous hurt by rash/negligent acts without intention."},
    {"context": "mact procedure compensation", "response": "MACT (Motor Accident Claims Tribunal) handles compensation claims. File within 6 months with medical reports, FIR copy, and income proof."},
    {"context": "motor accident claims tribunal", "response": "MACT is a special court for motor accident compensation. It provides speedy justice for accident victims and their families for claiming damages."},
    {"context": "mact claim documents required", "response": "MACT claim documents: FIR copy, medical records, death certificate (if applicable), income proof, age proof, dependency proof, post-mortem report, driving license, insurance details."},
    {"context": "mact compensation calculation", "response": "MACT compensation based on: Deceased/injured person's age, income, dependency, medical expenses, future earning capacity, pain and suffering, loss of consortium."},
    {"context": "mact time limit", "response": "MACT claims must be filed within 6 months from accident date. However, tribunal may condone delay up to 2 years with sufficient cause shown."},
    {"context": "who can file mact claim", "response": "MACT claim can be filed by: Accident victim, legal heirs in death cases, parents/guardians for minors, any person authorized by victim or legal heirs."},
    {"context": "mact interim compensation", "response": "MACT can award interim compensation for immediate needs like medical treatment. This is adjusted against final compensation amount decided later."},
    {"context": "mact appeal process", "response": "MACT awards can be appealed to High Court within 90 days. Supreme Court appeal possible if High Court dismisses or for substantial legal questions."},
    {"context": "bail procedure accident cases", "response": "For bailable offenses like 279, 337, bail can be obtained from police station or court. For 304A, 338, court bail may be required."},
    {"context": "anticipatory bail accident", "response": "Anticipatory bail available under Section 438 CrPC. File before arrest with High Court or Sessions Court when anticipating arrest in accident cases."},
    {"context": "regular bail accident", "response": "Regular bail filed after arrest. For bailable offenses, it's a right. For non-bailable offenses, court has discretion based on case circumstances."},
    {"context": "bail conditions accident cases", "response": "Common bail conditions: Surrender passport, not leave jurisdiction, report to police station, not tamper with evidence, not influence witnesses, pay compensation if ordered."},
    {"context": "bail amount accident cases", "response": "Bail amount varies based on: Offense severity, accused's financial status, flight risk, case circumstances. Can range from Rs. 10,000 to lakhs."},
    {"context": "when bail rejected", "response": "Bail rejected when: Flight risk exists, evidence tampering possibility, witness intimidation fear, repeat offender, serious offense with strong evidence."},
    {"context": "fir procedure accident", "response": "FIR should be filed immediately after accident at nearest police station. Include all details of accident, injuries, and vehicle information."},
    {"context": "fir mandatory details", "response": "FIR must include: Date, time, place of accident, vehicle details, driver details, nature of injuries, witness information, preliminary cause."},
    {"context": "fir filing time limit", "response": "No specific time limit for FIR, but should be filed immediately. Delay may raise questions about genuineness and may weaken the case."},
    {"context": "can fir be amended", "response": "FIR cannot be amended, but additional facts can be added through supplementary statements under Section 161 CrPC or additional FIR if required."},
    {"context": "fir copy how to get", "response": "FIR copy can be obtained free from police station under Right to Information Act. Court can also direct police to provide certified copy."},
    {"context": "zero fir in accidents", "response": "Zero FIR can be filed at any police station regardless of jurisdiction. It's transferred to concerned police station for investigation."},
    {"context": "hi", "response": "Hello! I'm your comprehensive Legal Accident Advisor. I can help with IPC sections, compensation procedures, court processes, and all legal aspects of accident cases. How can I assist you today?"},
    {"context": "hello", "response": "Welcome to your AI Legal Assistant! I specialize in accident laws, IPC sections 279, 304A, 337, 338, MACT procedures, insurance claims, and legal procedures. What would you like to know?"},
    {"context": "help", "response": "I can help you with: IPC Sections (279, 304A, 337, 338), MACT compensation claims, Court procedures, Evidence collection, Legal aid options, Insurance claims, Bail procedures, FIR filing, Settlement processes. What specific information do you need?"},
    {"context": "thanks", "response": "You're most welcome! I'm glad I could help with your legal queries. Remember to drive safely and follow traffic rules. Don't hesitate to ask if you have more questions!"},
    {"context": "bye", "response": "Goodbye! Drive safely and responsibly. Always follow traffic rules and maintain your vehicle properly. If you need more legal assistance, I'm here to help. Take care!"}
]

def clear_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def preprocess_input(user_input):
    user_input = user_input.lower().strip()
    user_input = re.sub(r'[^\w\s]', ' ', user_input)
    user_input = re.sub(r'\s+', ' ', user_input)
    return user_input

def context_aware_matching(user_input, dataset):
    user_input_processed = preprocess_input(user_input)
    user_words = set(user_input_processed.split())

    best_match = None
    best_score = 0

    for item in dataset:
        context_words = set(preprocess_input(item['context']).split())
        common_words = user_words.intersection(context_words)

        if common_words:
            score = len(common_words) / len(user_words.union(context_words))
            if score > best_score and score > 0.3:
                best_score = score
                best_match = item

    return best_match

def get_enhanced_fallback_response(user_input):
    user_input_lower = user_input.lower()

    matched_item = context_aware_matching(user_input, comprehensive_legal_dataset)
    if matched_item:
        return matched_item['response']

    comprehensive_fallbacks = {
        'ipc': "IPC (Indian Penal Code) sections related to accidents: 279 (rash driving), 304A (death by negligence), 337 (simple hurt by negligence), 338 (grievous hurt by negligence).",
        'section': "Which IPC section are you asking about? I can help with sections 279, 304A, 337, and 338 related to accident cases.",
        '279': "IPC Section 279: Rash/negligent driving on public way. Punishment: Up to 6 months imprisonment or Rs. 1000 fine or both. It's bailable and cognizable.",
        '304a': "IPC Section 304A: Death by negligence without intention. Punishment: Up to 2 years imprisonment or fine or both. Generally bailable.",
        'mact': "MACT (Motor Accident Claims Tribunal) handles compensation for accident victims. File within 6 months of accident with required documents.",
        'compensation': "Compensation through MACT (Motor Accident Claims Tribunal). File within 6 months with medical reports, FIR copy, income proof.",
        'bail': "Bail procedures: For bailable offenses (279, 337) - police/magistrate can grant. For non-bailable (304A, 338) - court discretion.",
        'help': "I can help with: IPC Sections (279, 304A, 337, 338), MACT procedures, bail processes, FIR filing, evidence collection, insurance claims.",
        'thanks': "You're welcome! Drive safely and follow traffic rules. Contact me anytime for legal guidance on accident-related matters.",
        'hello': "Hello! I'm your AI Legal Assistant specializing in accident laws and procedures. How can I help you today?",
        'hi': "Hi there! I provide information on accident laws, IPC sections, compensation procedures, and legal processes. What would you like to know?"
    }

    for keyword, response in comprehensive_fallbacks.items():
        if keyword in user_input_lower:
            return response

    return "I specialize in accident law and can help with IPC sections (279, 304A, 337, 338), MACT compensation, legal procedures, evidence collection, and court processes. Could you please be more specific about what you'd like to know?"

def generate_ai_response(user_input):
    try:
        if model is None or tokenizer is None:
            raise Exception("Model not loaded")

        input_text = f"legal question: {preprocess_input(user_input)}"

        input_ids = tokenizer(
            input_text,
            return_tensors='pt',
            max_length=512,
            truncation=True,
            padding=True
        ).input_ids.to(device)

        with torch.no_grad():
            outputs = model.generate(
                input_ids,
                max_length=300,
                num_beams=4,
                early_stopping=True,
                no_repeat_ngram_size=3,
                temperature=0.8,
                do_sample=True,
                top_k=50,
                top_p=0.95,
                pad_token_id=tokenizer.pad_token_id,
                repetition_penalty=1.2
            )

        response = tokenizer.decode(outputs[0], skip_special_tokens=True)
        clear_memory()
        return response.strip()

    except Exception as e:
        logger.error(f"AI generation failed: {e}")
        return None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global model, tokenizer, device
    try:
        logger.info("Loading T5 model...")
        model_name = "t5-small"
        tokenizer = T5Tokenizer.from_pretrained(model_name)
        model = T5ForConditionalGeneration.from_pretrained(model_name)

        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model.to(device)
        model.eval()

        logger.info(f"Model loaded successfully on {device}")
    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        model = None
        tokenizer = None

    yield

    logger.info("Shutting down...")

# Now create the FastAPI app with the lifespan function
app = FastAPI(
    title="AI Legal Accident Advisor",
    description="Specialized in Indian Accident Laws & Legal Procedures",
    version="1.0.0",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/", response_model=HealthResponse)
async def health_check():
    return HealthResponse(
        status="healthy",
        timestamp=datetime.now().isoformat(),
        model_loaded=model is not None
    )

@app.post("/chat")
async def chat_endpoint(query: Query):
    try:
        if not query.question.strip():
            raise HTTPException(status_code=400, detail="Question cannot be empty")

        logger.info(f"Received query: {query.question}")

        ai_response = generate_ai_response(query.question)

        if ai_response and len(ai_response.strip()) > 10:
            response = ai_response
        else:
            response = get_enhanced_fallback_response(query.question)

        return {
            "answer": response,
            "timestamp": datetime.now().isoformat(),
            "source": "ai" if ai_response else "fallback"
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in chat endpoint: {e}")
        response = get_enhanced_fallback_response(query.question)
        return {
            "answer": response,
            "timestamp": datetime.now().isoformat(),
            "source": "fallback",
            "error": "AI model unavailable"
        }

@app.get("/status")
async def get_status():
    return {
        "status": "online",
        "model_loaded": model is not None,
        "device": str(device) if device else "not_initialized",
        "dataset_size": len(comprehensive_legal_dataset),
        "timestamp": datetime.now().isoformat()
    }

@app.exception_handler(404)
async def not_found_handler(request, exc):
    return {"error": "Endpoint not found", "message": "Use /chat for queries or / for health check"}

@app.exception_handler(500)
async def internal_error_handler(request, exc):
    return {"error": "Internal server error", "message": "Please try again later"}

if __name__ == "__main__":
    import uvicorn
    import nest_asyncio
    nest_asyncio.apply()
    uvicorn.run(app, host="0.0.0.0", port=8000)